---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v2-managedclusters-apps.html 
summary: Listen Sie die Apps für einen verwalteten Cluster auf 
---
= Listen Sie die Apps für einen verwalteten Cluster auf
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v2/managedClusters/{managedCluster_id}/apps`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| managedCluster_id | Zeichenkette | Pfad | True  a| 
ID der enthaltenden managedCluster-Ressource



| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"

* Beispiel: id,name,state




| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#app_2_2_get_response_body["app_2.2_get_response_body"], array[]] | True  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | True  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-apps",
  "version": "2.2",
  "items": [
    [
      "2ff50f4b-fe40-4980-913f-8a4469184822",
      "mysql",
      "ready"
    ],
    [
      "ae1e6561-9e22-406c-8a5a-762f4604da00",
      "jenkins",
      "ready"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
targetSchema

[role="api-collapsible-fifth-title"]
accept-post

[role="api-collapsible-fifth-title"]
accept-put

[role="api-collapsible-fifth-title"]
Hinweise

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Status | Zeichenkette | Falsch  a| 



| erlauben | Array[string] | Falsch  a| 



| accept-post | link:#accept-post["accept-post"] | Falsch  a| 



| Berechtigungen | Array[string] | Falsch  a| 



| accept-put | link:#accept-put["accept-put"] | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_link

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| rel | Zeichenkette | True  a| 



| href | Zeichenkette | True  a| 



| Typ | Zeichenkette | Falsch  a| 



| targetSchema | link:#targetSchema["targetSchema"] | Falsch  a| 



| Titel | Zeichenkette | Falsch  a| 



| Hinweise | link:#hints["Hinweise"] | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
GVK

JSON-Objekt, das eine Kubernetes-Gruppe/Version/Kind enthält.

* Dieses Objekt wird intern gegen Astra/apiResources validiert.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Gruppe | Zeichenkette | True  a| 
JSON-Zeichenkette mit einer von Kubernetes zugewiesenen Gruppenkennung.

* Diese Zeichenkette wird intern gegen Astra/apiResources validiert




| Art | Zeichenkette | True  a| 
JSON-Zeichenkette, die einen von Kubernetes zugewiesenen Kindbezeichner enthält.

* Diese Zeichenkette wird intern gegen Astra/apiResources validiert




| Version | Zeichenkette | True  a| 
JSON-Zeichenkette mit einer von Kubernetes zugewiesenen Versionskennung.

* Diese Zeichenkette wird intern gegen Astra/apiResources validiert


|===
[role="api-collapsible-fifth-title"]
clusterScopedResources

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| GVK | link:#GVK["GVK"] | True  a| 
JSON-Objekt, das eine Kubernetes-Gruppe/Version/Kind enthält.

* Dieses Objekt wird intern gegen Astra/apiResources validiert.




| labelSelectors | Array[string] | Falsch  a| 
JSON-Array von JSON-Strings, das einen Label-Selektor für die clusterweiten GroupVersionKinds (GVKs) innerhalb des Clusters darstellt. Wenn dieses leer ist, werden alle GVK-Instanzen im Cluster einbezogen. Jedes Element in diesem Array ist ein Kubernetes-Label-Selektor-String und folgt derselben Grammatik für diese Werte. Beispiele:

* [ "app=mysql" ] -- Wählt alle Ressourcen aus, deren Label den Namen „app“ und den Wert „mysql“ hat. Weitere Beispiele finden Sie hier: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement[]


|===
[role="api-collapsible-fifth-title"]
namespaceScopedResources

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Namensraum | Zeichenkette | True  a| 
JSON-Zeichenkette mit dem Namen eines Namespace, in dem die Anwendung definiert ist. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 253
* Entspricht dem DNS 1123 Label Schema




| labelSelectors | Array[string] | True  a| 
JSON-Array von JSON-Strings, das einen Label-Selektor innerhalb des Namespace darstellt. Ist das Array leer, werden alle Ressourcen im Namespace eingeschlossen. Jedes Element in diesem Array ist ein Kubernetes-Label-Selektor-String und folgt der Grammatik für diese Werte. Beispiele:

* [ "app=mysql" ] -- Wählt alle Ressourcen aus, die ein Label mit dem Namen „app“ und dem Wert „mysql“ haben.
* [ "app != mysql" ] -- Wählt alle Ressourcen aus, deren Label den Namen „app“ hat und deren Wert nicht „mysql“ ist
* [ "app in (mysql, mariadb)" ] -- Wählt alle Ressourcen aus, deren Label „app“ heißt und deren Wert „mysql“ oder „mariadb“ ist
* [ "app notin (nginx, wordpress)" ] -- Wählt alle Ressourcen aus, die kein Label mit dem Namen app und den Werten nginx oder wordpress haben
* [ "app" ] -- Wählen Sie alle Ressourcen aus, die ein Label mit dem Namen app haben
* [ "!app" ] -- Wählt alle Ressourcen aus, die keine Bezeichnung namens „app“ haben. Beachten Sie, dass mehrere Auswahloperatoren durch Kommas getrennt in einem einzigen Selektor angegeben werden können. In diesem Fall werden die Ergebnisse der einzelnen Auswahloperatoren mit UND verknüpft.
* [ "app=mysql,version=2" ] -- Wählt alle Ressourcen aus, die ein Label mit dem Namen „app“ und dem Wert „mysql“ sowie ein Label mit dem Namen „version“ und dem Wert „2“ besitzen


|===
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| aus | Zeichenkette | True  a| 



| : | Array[string] | True  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
namespaceMapping

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Quelle | Zeichenkette | True  a| 
JSON-Zeichenkette mit dem Namen des Namespace im Quell-Cluster. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 253
* Entspricht dem DNS 1123 Label Schema




| Ziel | Zeichenkette | True  a| 
JSON-Zeichenkette mit dem Namen des Namespace im Ziel-Cluster. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 253
* Entspricht dem DNS 1123 Label Schema


|===
[role="api-collapsible-fifth-title"]
storageClassMapping

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Quelle | Zeichenkette | True  a| 
JSON-Zeichenkette mit dem Namen der Quellspeicherklasse. Kann auch '*' sein, um alle Quellspeicherklassen anzugeben. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63
* Entspricht dem DNS 1123 Label Schema, wenn ein Speicherklassenname verwendet wird
* '*' zur Angabe aller Speicherklassen




| Ziel | Zeichenkette | True  a| 
JSON-Zeichenkette mit dem Namen der Zielspeicherklasse. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63
* Entspricht dem DNS 1123 Label Schema


|===
[role="api-collapsible-fifth-title"]
GVKN

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Gruppe | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer von Kubernetes zugewiesenen Gruppenkennung.

* Diese Zeichenkette wird intern gegen Astra/apiResources validiert




| Version | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer von Kubernetes zugewiesenen Versionskennung.

* Diese Zeichenkette wird intern gegen Astra/apiResources validiert




| Art | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die einen von Kubernetes zugewiesenen Kindbezeichner enthält.

* Diese Zeichenkette wird intern gegen Astra/apiResources validiert




| Namensräume | Array[string] | Falsch  a| 
JSON-Array von JSON-Zeichenketten, die die Namensräume beschreiben, aus denen Ressourcen ein- oder ausgeschlossen werden sollen. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63
* Entspricht dem DNS 1123 Label Schema




| Namen | Array[string] | Falsch  a| 
JSON-Array mit JSON-Zeichenketten, die die Namen der Kubernetes-Ressourcen beschreiben, die in die selektive Wiederherstellung einbezogen oder ausgeschlossen werden sollen. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 253
* Entspricht dem DNS 1123 Label Schema




| labelSelectors | Array[string] | Falsch  a| 
JSON-Array mit JSON-Strings, die Kubernetes-Label-Selektoren beschreiben, welche zum Ein- oder Ausschließen von Ressourcen bei der selektiven Wiederherstellung verwendet werden. Jedes Element in diesem Array ist ein Kubernetes-Label-Selektor-String und folgt derselben Grammatik für diese Werte. Beispiele:

* [ "app=mysql" ] -- Wählt alle Ressourcen aus, deren Label den Namen „app“ und den Wert „mysql“ hat. Weitere Beispiele finden Sie hier: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement[]


|===
[role="api-collapsible-fifth-title"]
restoreFilter

JSON-Objekt mit einer Liste von Filtern, die beschreiben, welche Ressourcen in eine selektive Wiederherstellung einbezogen oder ausgeschlossen werden. Ein- und Ausschlusskriterien schließen sich gegenseitig aus, und eine selektive Wiederherstellung kann nur einen Filtertyp verwenden.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| resourceSelectionCriteria | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der angibt, wie Ressourcenfilter Ressourcen auswählen. Gültige Werte sind include oder exclude.



| GVKN | Array[link:#GVKN["GVKN"]] | Falsch  a| 
Ein JSON-Array von JSON-Objekten beschreibt Ressourcen, die bei einer selektiven Wiederherstellung gefiltert werden sollen. Eine Ressource entspricht einem einzelnen GVKN-Filterelement, wenn alle angegebenen Filterfelder mit dem entsprechenden Ressourcenfeld übereinstimmen. Filterfelder, die Arrays sind (z. B. Namespaces und Namen), entsprechen einem Feld, wenn mindestens eines ihrer Elemente mit dem entsprechenden Ressourcenfeld übereinstimmt. Das Feld labelSelectors erfordert, dass alle Selektoren übereinstimmen. Eine Ressource, die einem Filter im Array von GVKN-Filterobjekten entspricht, wird je nach resourceSelectionCriteria-Wert in die Wiederherstellung einbezogen oder ausgeschlossen. Leere GVKN-Objekte führen zu einem Validierungsfehler.

|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
app_2.2_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-app"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "2,0"
* "2,1"
* "2,2"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| Links | Array[link:#type_astra_link["type_astra_link"]] | True  a| 
Links mit Beschreibungen der unterstützten Operationen für die Ressource.



| Name | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Namen für die Anwendung. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63
* Diese Zeichenkette wird intern validiert, um XSS-, Unicode-, Directory-Traversal- und SQL-Injection-Angriffe zu verhindern.
* Entspricht dem DNS 1123 Label Schema




| clusterScopedResources | Array[link:#clusterScopedResources["clusterScopedResources"]] | Falsch  a| 
JSON-Array von JSON-Objekten, die die clusterweiten Ressourcen beschreiben, die Teil dieser App sind



| namespaceScopedResources | Array[link:#namespaceScopedResources["namespaceScopedResources"]] | True  a| 
JSON-Array von JSON-Objekten, die die Ressourcen beschreiben, die Teil dieser App sind



| lastResourceCollectionTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit dem Zeitstempel, wann die letzte Ressourcenerfassung durchgeführt wurde. Dieses Feld ist nicht gesetzt, wenn für diese Anwendung noch keine Ressourcenerfassung durchgeführt wurde. Folgende Werte sind definiert:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Zustand | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der den Betriebszustand der Anwendung angibt. Folgende Werte sind definiert:

* „pending“ – Die Applikation ist zur Erkennung vorgesehen
* „discovering“ – Die Anwendung befindet sich im Entdeckungsprozess
* „Bereitstellung“ – Die Anwendung wird gerade bereitgestellt
* „ready“ – Die Anwendung läuft normal
* „failed“ – Die Anwendung befindet sich in einem permanenten Fehlerzustand
* „Wiederherstellung“ – Die Anwendung wird aus einer Sicherung oder einem Snapshot wiederhergestellt
* „Nicht verfügbar“ – Die Anwendung ist momentan nicht zugänglich
* "unbekannt" – Der Anwendungsstatus kann nicht ermittelt werden
* „Wird gelöscht“ – Die Anwendung wird gerade gelöscht




| stateTransitions | Array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Falsch  a| 
JSON-Array von JSON-Objekten, die jeweils die Menge der zulässigen Zustandsübergänge von einem definierten Zustand aus darstellen. Jedes JSON-Objekt enthält die Felder "from" und "to", wobei der Wert von "from" der Name eines Zustands ist und der Wert von "to" ein Array zulässiger Zielzustände ist.



| stateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | True  a| 
JSON-Array von JSON-Objekten, das zusätzliche Details zum aktuellen Zustand auflistet, einschließlich der Gründe, warum der aktuelle Zustand erreicht wurde. Sind keine Details verfügbar, ist dieses Array leer. Folgende Werte sind definiert:

* Mindestanzahl: 0




| protectionState | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der den Schutzstatus der Anwendung angibt. Folgende Werte sind definiert:

* „geschützt“ – Für die Anwendung ist eine Datensicherungsstrategie definiert und sie entspricht dieser Strategie
* „Teilweise“ – Die Anwendung hat eine Datensicherungsstrategie definiert, entspricht dieser jedoch nicht.
* "keine" – Für die Anwendung ist keine Datensicherungsstrategie definiert
* "atRisk" – Die standardmäßige Speicherklasse des Clusters unterstützt keine Snapshots, die Anwendung läuft Gefahr, ein nicht unterstütztes Volume zu erhalten




| protectionStateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | True  a| 
Ein JSON-Array mit JSON-Objekten, das zusätzliche Details zum aktuellen Schutzstatus auflistet, einschließlich der Gründe, warum der aktuelle Status erreicht wurde. Sind keine Details verfügbar, ist dieses Array leer. Folgende Werte sind definiert:

* Mindestanzahl: 0




| appDetectedType | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die den spezifischen erkannten Anwendungstyp eindeutig repräsentiert. Folgende Werte sind definiert:

* "system" – Die Anwendung enthält eine Ressource, die sie als Teil der Kubernetes-Umgebung kennzeichnet.
* "acc" - Die Anwendung enthält Ressourcen, die sie als Astra Control Center-Instanz identifizieren




| Namensräume | Array[string] | True  a| 
JSON-Array von JSON-Zeichenketten, die die Namen der Namespaces enthalten, in denen die Anwendung ausgeführt wird. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 253
* Entspricht dem DNS 1123 Label Schema




| namespaceMapping | Array[link:#namespaceMapping["namespaceMapping"]] | Falsch  a| 
JSON-Array von JSON-Objekten, die jeweils einen Quell-Namespace einem Ziel-Namespace für einen Klonvorgang zuordnen. Folgende Werte sind definiert:

* Mindestanzahl: 0




| storageClassMapping | Array[link:#storageClassMapping["storageClassMapping"]] | Falsch  a| 
JSON-Array von JSON-Objekten, die jeweils eine Quellspeicherklasse einer Zielspeicherklasse für einen Wiederherstellungsvorgang zuordnen. Sind keine Elemente vorhanden oder ist das Feld nicht vorhanden, werden die ursprünglichen Quellspeicherklassennamen verwendet. Folgende Werte sind definiert:

* Mindestanzahl: 0




| clusterName | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem Namen des Clusters, auf dem die Anwendung ausgeführt wird. Wird nicht zurückgegeben, wenn die Anwendung nicht ausgeführt wird.



| Cluster-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der ID des Clusters, auf dem die Anwendung ausgeführt wird. Wird nicht zurückgegeben, wenn die Anwendung nicht ausgeführt wird. Bei der Erstellung angegeben, gibt clusterID an, in welchen Cluster die Anwendung geklont werden soll. Existiert der angegebene Cluster nicht oder stimmt die clusterID nicht mit der in der Anforderungs-URI angegebenen überein, schlägt der Klonvorgang fehl. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| clusterType | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den Clustertyp angibt. Folgende Werte sind definiert:

* "gke" - Kubernetes, gehostet auf Google Kubernetes Engine (GKE)
* "aks" – Kubernetes, gehostet auf Microsoft Azure Kubernetes Service (AKS)
* "eks" - Kubernetes, gehostet auf Amazon Elastic Kubernetes Service (Amazon EKS)
* "openshift" - Der Cluster ist vom Typ OpenShift
* "kubernetes" - Der Cluster ist ein generisches Kubernetes




| sourceAppID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der ID einer Quellanwendung. Wird nur zurückgegeben, wenn die Anwendung von einer anderen Anwendung geklont oder aus einer Sicherung oder einem Snapshot wiederhergestellt wurde. Bei der Erstellung wird die sourceAppID zusammen mit der sourceClusterID verwendet und gibt an, welche laufende Anwendung geklont wird. Existiert die angegebene Anwendung nicht im angegebenen Quell-Cluster, schlägt der Klonvorgang fehl. Bei der Erstellung einer Anwendung kann nur entweder sourceAppID, backupID oder snapshotID angegeben werden. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| sourceClusterName | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem Namen des Clusters, auf dem die Anwendung zuvor ausgeführt wurde. Wird nur zurückgegeben, wenn die Anwendung von einem anderen Cluster geklont wurde.



| Quell-Cluster-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der ID des Clusters, auf dem die Anwendung zuvor ausgeführt wurde. Wird nur zurückgegeben, wenn die Anwendung von einem anderen Cluster geklont wurde. Bei der Erstellung wird die sourceClusterID zusammen mit der sourceAppID verwendet und gibt den Quell-Cluster der zu klonenden Anwendung an. Wenn der angegebene Quell-Cluster nicht existiert, schlägt der Klonvorgang fehl. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Backup-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der ID des Backups, aus dem die Anwendung wiederhergestellt wurde. Wird nur zurückgegeben, wenn die Anwendung aus einem Backup wiederhergestellt wurde. Bei der Erstellung gibt backupID an, dass eine Anwendung aus einem vorhandenen Backup geklont wird. Existiert das angegebene Backup nicht, schlägt das Klonen fehl. Bei der Erstellung einer Anwendung kann nur entweder sourceAppID, backupID oder snapshotID angegeben werden. Bei einer Ersetzung gibt backupID das Anwendungs-Backup an, aus dem die Anwendung direkt wiederhergestellt wird. Existiert das angegebene Backup nicht, schlägt die Wiederherstellung fehl. Beim Aktualisieren einer Anwendung kann nur entweder backupID oder snapshotID angegeben werden. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| snapshotID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der ID des Snapshots, aus dem die Anwendung wiederhergestellt wurde. Wird nur zurückgegeben, wenn die Anwendung aus einem Snapshot wiederhergestellt wurde. Bei der Erstellung einer Anwendung gibt snapshotID an, dass die Anwendung aus einem vorhandenen Snapshot geklont wird. Existiert der angegebene Snapshot nicht, schlägt der Klonvorgang fehl. Bei der Erstellung einer Anwendung kann nur entweder sourceAppID, backupID oder snapshotID angegeben werden. Bei einer Ersetzung einer Anwendung gibt snapshotID den Anwendungssnapshot an, aus dem die Anwendung direkt wiederhergestellt wird. Existiert der angegebene Snapshot nicht, schlägt die Wiederherstellung fehl. Bei der Aktualisierung einer Anwendung kann nur entweder backupID oder snapshotID angegeben werden. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Replikationsquellen-AppID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der ID der Anwendung, die in diese Anwendung repliziert wird. Wird nur zurückgegeben, wenn die Anwendung aktuell das Ziel in einer AppMirror-Beziehung ist und sich die Beziehung nicht im failedOver-Status befindet. Befindet sich die Beziehung im failedOver-Status, wird dieses Feld nicht zurückgegeben. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| restoreFilter | link:#restoreFilter["restoreFilter"] | Falsch  a| 
JSON-Objekt mit einer Liste von Filtern, die beschreiben, welche Ressourcen in eine selektive Wiederherstellung einbezogen oder ausgeschlossen werden. Ein- und Ausschlusskriterien schließen sich gegenseitig aus, und eine selektive Wiederherstellung kann nur einen Filtertyp verwenden.



| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====