---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-core-v1-users-groups.html 
summary: Gruppen für einen Benutzer auflisten 
---
= Gruppen für einen Benutzer auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users/{user_id}/groups`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Benutzer-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Benutzerressource



| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"

* Beispiel: id,authProvider,authID




| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"



| Orderby | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Sortierreihenfolge der Ressourcen beim Auflisten einer Sammlung an.

URL-Beispiele: "orderBy=name", "orderBy=name%20desc"

OpenAPI-Beispiele: "name desc"



| überspringen | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Anzahl der Ressourcen an, die beim Auflisten einer Sammlung übersprungen werden sollen.

URL-Beispiele: "skip=1"

OpenAPI-Beispiele: "1"



| Zählen | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, ob die Gesamtzahl der Ressourcen im Metadatenobjekt zurückgegeben werden soll.

URL-Beispiele: "count=true"

OpenAPI-Beispiele: "true"



| fortfahren |  | Abfrage | Falsch  a| 
Gibt das Token an, von dem aus die Auflistung fortgesetzt werden soll.

URL-Beispiele: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

OpenAPI-Beispiele: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#group_1_1_get_response_body["group_1.1_get_response_body"], array[]] | True  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | True  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-groups",
  "version": "1.1",
  "items": [
    [
      "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa",
      "ldap",
      "CN=Testers,CN=groups,DC=example,DC=com"
    ],
    [
      "e324ec3a-706d-4f57-a95d-1d88c03e7b73",
      "ldap",
      "CN=Admins,CN=groups,DC=example,DC=com"
    ],
    [
      "3070c84d-129b-4017-82a8-2c26a42dd77e",
      "ldap",
      "CN=SREs,CN=groups,DC=example,DC=com"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
group_1.1_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-group"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"
* "1,1"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | True  a| 
Der Name der Gruppenressource. Falls beim Erstellen nicht angegeben, wird der Wert auf

* erster Common Name (CN) Relative Distinguished Names (RDN), falls in der authID gefunden,
* authID, andernfalls. Wird beim Aktualisieren kein Wert angegeben, bleibt der Wert unverändert erhalten. Folgende Werte sind definiert:
* Mindestlänge: 1
* Maximale Länge: 2048




| authProvider | Zeichenkette | True  a| 
Der Authentifizierungsanbieter für die Gruppenressource. Folgende Werte sind definiert:

* "ldap"




| authID | Zeichenkette | True  a| 
Der Distinguished Name (DN) einer LDAP-Gruppe. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 2048




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====