---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-settings-.html 
summary: Eine Einstellung abrufen 
---
= Eine Einstellung abrufen
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/settings/{setting_id}`#

Gibt die gespeicherte Setting-API-Ressource im JSON-Antworttext zurück.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Einstellungs-ID | Zeichenkette | Pfad | True  a| 
ID der aufzulistenden Einstellungssammlung

|===


== Antwort

[source]
----
Status: 200, Returns the stored Setting API resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-setting"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"
* "1,1"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Namen für die Einstellung in hierarchischer Punktnotation (.). Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63
* Diese Zeichenkette wird intern validiert, um XSS-, Unicode-, Directory-Traversal- und SQL-Injection-Angriffe zu verhindern. Dieser Wert wird durch die zur Laufzeit geladene configmap festgelegt und kann vom Benutzer nicht geändert werden.




| currentConfig | link:#type_json["type_json"] | True  a| 
Ein JSON-Objekt mit Schlüsseln und Werten, die die aktuelle Konfiguration für diese Einstellung bilden. Der Inhalt dieses Objekts muss dem im configSchema-Feld enthaltenen JSON-Schema entsprechen. Standardwerte werden von der configmap bereitgestellt. Nachdem die Standardwerte vom Benutzer geändert wurden, werden sie nicht überschrieben.



| desiredConfig | link:#type_json["type_json"] | Falsch  a| 
Ein JSON-Objekt mit Schlüsseln und Werten, die die angeforderte Konfiguration für diese Einstellung bilden. Der Inhalt dieses Objekts muss dem im configSchema Feld enthaltenen JSON-Schema entsprechen. Das Objekt existiert erst, wenn es angegeben wurde. Wenn angegeben, veranlasst dies den Feature-Service, den entsprechenden Service zu benachrichtigen, damit die gewünschte Konfiguration angefordert werden kann. Der entsprechende Service kann dann die Validierung durchführen und die gewünschte Konfiguration auf die aktuelle Konfiguration anwenden.



| configSchema | link:#type_json_schema["type_json_schema"] | True  a| 
JSON-Objekt, das das JSON-Schema für die config-Eigenschaft in dieser Ressource enthält. Muss JSON Schema Draft 7 entsprechen. Wenn config-Werte in der Ressource vorhanden sind, ist die Validierung gegen das angegebene configSchema obligatorisch. Als allgemeine Konvention wird empfohlen, dass Konfigurationen ein "isEnabled"-Feld haben, wenn angemessen. Das "isEnabled"-Feld enthält einen Wert, der angibt, ob die Einstellung eingeschaltet ("true") oder ausgeschaltet ("false") ist.



| Zustand | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der den Betriebszustand der Anwendung angibt. Folgende Werte sind definiert:

* "gültig" - Die aktuelle Konfiguration entspricht der gewünschten Konfiguration.
* "Ausstehend" - Die gewünschte Konfiguration wird angewendet.
* "Fehler" - Die gewünschte Konfiguration kann nicht angewendet werden.




| stateUnready | Array[string] | True  a| 
JSON-Array von JSON-Zeichenketten, die jeweils einen Grund dafür angeben, warum die Einstellung nicht erfolgreich angewendet wurde. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 127




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Aktualisieren nichts anderes angegeben wird, werden die Bezeichnungen, creationTimestamp und createdBy des Metadatenobjekts unverändert beibehalten.


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-setting",
  "version": "1.1",
  "id": "ea510866-47d3-5130-8468-563df4cd6a28",
  "name": "astra.account.smtp",
  "currentConfig": {
    "credential": "",
    "isEnabled": "false",
    "port": 587,
    "relayServer": "smtp.sendgrid.net"
  },
  "configSchema": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "astra.account.smtp",
    "type": "object",
    "properties": {
      "credential": {
        "type": "string",
        "description": "The credential ID for SMTP authentication."
      },
      "isEnabled": {
        "type": "string",
        "description": "This property determines if this setting is enabled or not."
      },
      "port": {
        "type": "integer",
        "description": "The SMTP port. For an unencrypted or a TLS connection, use port 25, 2525, or 587."
      },
      "relayServer": {
        "type": "string",
        "description": "This setting is sometimes referred to as the external SMTP server or the SMTP relay."
      }
    },
    "additionalProperties": false,
    "required": [
      "relayServer",
      "port",
      "isEnabled"
    ]
  },
  "state": "valid",
  "stateUnready": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Antwort

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_json

Ein JSON-Objekt mit Schlüsseln und Werten, die die aktuelle Konfiguration für diese Einstellung bilden. Der Inhalt dieses Objekts muss dem im configSchema-Feld enthaltenen JSON-Schema entsprechen. Standardwerte werden von der configmap bereitgestellt. Nachdem die Standardwerte vom Benutzer geändert wurden, werden sie nicht überschrieben.

[role="api-collapsible-fifth-title"]
type_json

Ein JSON-Objekt mit Schlüsseln und Werten, die die angeforderte Konfiguration für diese Einstellung bilden. Der Inhalt dieses Objekts muss dem im configSchema Feld enthaltenen JSON-Schema entsprechen. Das Objekt existiert erst, wenn es angegeben wurde. Wenn angegeben, veranlasst dies den Feature-Service, den entsprechenden Service zu benachrichtigen, damit die gewünschte Konfiguration angefordert werden kann. Der entsprechende Service kann dann die Validierung durchführen und die gewünschte Konfiguration auf die aktuelle Konfiguration anwenden.

[role="api-collapsible-fifth-title"]
Eigenschaften

[role="api-collapsible-fifth-title"]
type_json_schema

JSON-Objekt, das das JSON-Schema für die config-Eigenschaft in dieser Ressource enthält. Muss JSON Schema Draft 7 entsprechen. Wenn config-Werte in der Ressource vorhanden sind, ist die Validierung gegen das angegebene configSchema obligatorisch. Als allgemeine Konvention wird empfohlen, dass Konfigurationen ein "isEnabled"-Feld haben, wenn angemessen. Das "isEnabled"-Feld enthält einen Wert, der angibt, ob die Einstellung eingeschaltet ("true") oder ausgeschaltet ("false") ist.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| $schema | Zeichenkette | True  a| 



| Typ | Zeichenkette | True  a| 



| Eigenschaften | link:#properties["Eigenschaften"] | True  a| 



| additionalProperties | boolescher Wert | True  a| 



| erforderlich | Array[string] | True  a| 

|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Aktualisieren nichts anderes angegeben wird, werden die Bezeichnungen, creationTimestamp und createdBy des Metadatenobjekts unverändert beibehalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====