---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-hooksources.html 
summary: Alle Hook-Quellen auflisten 
---
= Alle Hook-Quellen auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/hookSources`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"



| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#hookSource_1_0_get_response_body["hookSource_1.0_get_response_body"], array[]] | True  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | True  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-hookSources",
  "version": "1.0",
  "items": [
    {
      "type": "application/astra-hookSource",
      "version": "1.0",
      "id": "2d6154dd-6863-4a26-8017-6be092b8b0bd",
      "name": "Payroll script",
      "private": "false",
      "preloaded": "false",
      "sourceType": "script",
      "source": "ZWNobyAiVkhKaGJuTWdVbWxuYUhSeklRPT0iIHwgYmFzZTY0IC1k",
      "sourceMD5Checksum": "b1a4b8b0144c3f6be553b626130ca145",
      "description": "Pre and post hook script for payroll",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "64182074-ddb6-42eb-b7f4-b6a02cf9ba7c"
      }
    },
    {
      "type": "application/astra-hookSource",
      "version": "1.0",
      "id": "b71c6793-aa9b-4654-92ef-60663a0aedac",
      "name": "Payroll script",
      "private": "true",
      "preloaded": "false",
      "sourceType": "script",
      "sourceMD5Checksum": "6469094cb279f6d91358bc5062d15baf",
      "description": "Pre and post hook script for payroll",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-08T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-08T12:24:52.256624Z",
        "createdBy": "64182074-ddb6-42eb-b7f4-b6a02cf9ba7c"
      }
    },
    {
      "type": "application/astra-hookSource",
      "version": "1.0",
      "id": "682fe9d2-52d2-4c30-bcec-ecefddde359c",
      "name": "NetApp preloaded ",
      "private": "true",
      "preloaded": "false",
      "sourceType": "script",
      "sourceMD5Checksum": "7864495443c1087104520a320a2225c9",
      "description": "NetApp Postgres preloaded snapshot pre and post",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-07-12T12:24:52.256624Z",
        "modificationTimestamp": "2020-07-12T12:24:52.256624Z",
        "createdBy": "4428cfd4-27fd-4248-9f49-bd3a02043ab8"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
hookSource_1.0_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-hookSource"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem benutzerdefinierten Namen für die Ressource. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63 Der Name muss innerhalb aller Hook-Quellressourcen eindeutig sein.




| Privat | Zeichenkette | True  a| 
JSON-Zeichenkette, die angibt, ob das Quellfeld in APIs verfügbar gemacht oder absichtlich leer gelassen wird. Folgende Werte sind definiert:

* "true" - Der Quellwert ist privat und wird nicht über die API offengelegt.
* "false" - Der Quellwert ist nicht privat und wird über die API offengelegt.




| vorinstalliert | Zeichenkette | True  a| 
JSON-Zeichenkette, die angibt, ob die Quelle vorgeladen wurde. Folgende Werte sind definiert:

* "true" - Die Quelle wurde vorgeladen.
* "false" - Die Quelle wurde nicht vorgeladen. Vorgeladene Hook-Quellressourcen sind schreibgeschützt.




| sourceType | Zeichenkette | True  a| 
JSON-Zeichenkette, die den Hook-Quelltyp definiert. Folgende Werte sind definiert:

* „Skript“ – Shell-Skript. Der Klartextquelltext darf keine Binärdaten oder Wagenrücklaufzeichen enthalten, andernfalls wird ein Fehler zurückgegeben.




| Quelle | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem auszuführenden Skript im Base64-Format. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 131072
* Entspricht dem Base64-kodierten Datenschema. Die maximale Größe eines Quellwerts beträgt 128 KiB bei der Base64-Kodierung.




| sourceMD5Checksum | Zeichenkette | True  a| 
JSON-Zeichenkette mit der MD5-Prüfsumme des Werts des Schlüssels „source“. Folgende Werte sind definiert:

* Der definierte reguläre Ausdruck lautet: "^([0-9a-fA-F]){32}$"




| description | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer benutzerdefinierten Beschreibung der Hook-Quelle. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 511




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====