---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-ldapgroups-.html 
summary: Eine LDAP-Gruppe abrufen 
---
= Eine LDAP-Gruppe abrufen
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/ldapGroups/{ldapGroup_id}`#

Gibt ein JSON-Objekt zurück, das die gespeicherte LDAP-Ressource repräsentiert.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| ldapGroup_id | Zeichenkette | Pfad | True  a| 
ID der ldapGroup-Sammlung, die aufgelistet werden soll

|===


== Antwort

[source]
----
Status: 200, Returns a JSON object representing the stored LDAP resource.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-ldapGroup"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| cn | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die den LDAP-Gruppennamen darstellt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63




| individueller Name | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die den individuellen Name der LDAP-Gruppe darstellt. Folgende Werte sind definiert:

* Entspricht RFC 4514




| Metadaten | link:#type_astra_metadata["type_astra_metadata"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra Metadatenschema


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-ldapGroup",
  "version": "1.0",
  "id": "cb05a289-a7a1-502c-a2bc-7e75dba8fddc",
  "cn": "boulder_sysadmins",
  "dn": "cn=boulder_sysadmins,ou=groups,dc=example,dc=com",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra Metadatenschema


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | True  a| 



| CreationZeitstempel | Zeichenkette | True  a| 



| Änderungszeitstempel | Zeichenkette | True  a| 



| Erstellt von | Zeichenkette | True  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====