---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clouds-clusters-storageclasses-.html 
summary: Eine Speicherklasse für eine Cloud abrufen 
---
= Eine Speicherklasse für eine Cloud abrufen
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds/{cloud_id}/clusters/{cluster_id}/storageClasses/{storageClass_id}`#

Gibt die gespeicherte Storage Class API-Ressource im JSON-Antworttext zurück.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| cloud_id | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Cloud-Ressource



| Cluster-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Clusterressource



| Speicherklassen-ID | Zeichenkette | Pfad | True  a| 
ID der storageClass-Sammlung, die aufgelistet werden soll

|===


== Antwort

[source]
----
Status: 200, Returns the stored Storage Class API resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-storageClass"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"
* "1,1"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der den Namen der Speicherklasse angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 255




| Bereitsteller | Zeichenkette | True  a| 
JSON-Zeichenfolge mit einem Wert, der den der Speicherklasse zugeordneten Provisioner angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 255




| verfügbar | Zeichenkette | True  a| 
JSON-Zeichenfolge, die angibt, ob die Speicherklasse für den Cluster verfügbar ist oder ob sie dem Cluster während der Verwaltung hinzugefügt werden kann. Folgende Werte sind definiert:

* "verfügbar" - Die Speicherklasse steht zur Nutzung zur Verfügung
* „eligible“ – Die Speicherklasse kann vom Cluster verwendet werden, wenn dieser verwaltet wird.
* "nicht berechtigt" - Die Speicherklasse ist nicht berechtigt, vom Cluster verwendet zu werden, wenn sie unter Verwaltung steht.




| allowVolumeExpansion | Zeichenkette | True  a| 
JSON-Zeichenkette, die angibt, ob die Speicherklasse eine Volumenerweiterung zulässt. Folgende Werte sind definiert:

* "wahr" - Die Speicherklasse ermöglicht die Volumenerweiterung
* "false" – Die Speicherklasse erlaubt keine Volumenerweiterung
* „Nicht verfügbar“ – Es ist nicht bekannt, ob die Speicherklasse eine Volumenerweiterung zulässt




| reclaimPolicy | Zeichenkette | True  a| 
JSON-Zeichenfolge mit einem Cloud-spezifischen Wert, der die Aufbewahrungsrichtlinie der Speicherklasse angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 255




| volumeBindingMode | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Cloud-spezifischen Wert, der den Bindungsmodus für die Speicherklasse angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 255




| isDefault | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die angibt, ob die Speicherklasse die Standardannotation enthält. Folgende Werte sind definiert:

* "true" - Die Speicherklasse enthält die Standardannotation




| maxSnapshotCount | Nummer | Falsch  a| 
JSON-Zahl, die angibt, wie viele Snapshots unterstützt werden. Diese Informationen werden den von NetApp bereitgestellten Speicherklassen zugeordnet.



| maxBackupCount | Nummer | Falsch  a| 
JSON-Zahl, die angibt, wie viele Backups unterstützt werden. Diese Informationen werden den von NetApp bereitgestellten Speicherklassen zugeordnet.



| Preis | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die die Währungseinheiten pro Zeiteinheit für die Speicherklasse angibt. Diese Informationen werden den von NetApp bereitgestellten Speicherklassen zugeordnet. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63




| Währung | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem dreistelligen ISO-4217-Währungscode, in dem der Preis angegeben ist. Diese Information ist den von NetApp bereitgestellten Speicherklassen zugeordnet. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 255




| Leistung | Nummer | Falsch  a| 
JSON-Zahl, die das Leistungsziel (Service Level Objective, SLO) in MBps angibt. Diese Informationen werden den von NetApp bereitgestellten Speicherklassen zugeordnet.



| Widerstandsfähigkeit | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die die Resilienzkonfiguration für den Speicher angibt. Diese Informationen werden den von NetApp bereitgestellten Speicherklassen zugeordnet. Folgende Werte sind definiert:

* „regional“ – Das Volume ist nicht mehr verfügbar, wenn eine bestimmte Region nicht verfügbar ist
* „multisite“ – Das Volume bleibt auch dann verfügbar, wenn eine bestimmte Region nicht erreichbar ist.




| Metadaten | link:#type_astra_metadata["type_astra_metadata"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra Metadatenschema


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageClass",
  "version": "1.1",
  "id": "ad9be22b-53c7-540c-8647-76afe2878952",
  "name": "my-storage-class",
  "provisioner": "csi.trident.netapp.io",
  "available": "eligible",
  "allowVolumeExpansion": "true",
  "reclaimPolicy": "recycle",
  "volumeBindingMode": "immediate",
  "isDefault": "true",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra Metadatenschema


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | True  a| 



| CreationZeitstempel | Zeichenkette | True  a| 



| Änderungszeitstempel | Zeichenkette | True  a| 



| Erstellt von | Zeichenkette | True  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====