---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-k8s-v1-apps-appbackups-appassets-.html 
summary: Abrufen einer Anwendungsressource aus einer Anwendungssicherung für eine App 
---
= Abrufen einer Anwendungsressource aus einer Anwendungssicherung für eine App
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appBackups/{appBackup_id}/appAssets/{appAsset_id}`#

Gibt die gespeicherte Application Asset API-Ressource im JSON-Antworttext zurück.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| App-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten App-Ressource



| appBackup_id | Zeichenkette | Pfad | True  a| 
ID der enthaltenden appBackup-Ressource



| appAsset_id | Zeichenkette | Pfad | True  a| 
ID der appAsset-Sammlung, die aufgelistet werden soll

|===


== Antwort

[source]
----
Status: 200, Returns the stored Application Asset API resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-appAsset"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"
* "1,1"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| assetType | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der angibt, welcher Asset-Typ von Kubernetes beschrieben wird. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 254




| CreationZeitstempel | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Kubernetes-Metadaten erstellt wurden. Folgende Werte sind definiert:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| GVK | link:#GVK["GVK"] | True  a| 
JSON-Objekt, das eine Kubernetes-Gruppe/Version/Kind enthält.



| Ressource | link:#type_json["type_json"] | Falsch  a| 
JSON-Objekt, das den gesamten Inhalt der Kubernetes-Ressourcendefinition enthält.



| Asset-ID | Zeichenkette | True  a| 
JSON-Zeichenkette mit einer von Kubernetes zugewiesenen Kennung. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Etiketten | Array[link:#labels["Etiketten"]] | True  a| 
JSON-Array von JSON-Objekten, die jeweils ein dem Asset zugeordnetes Kubernetes-Label enthalten. Sind keine Details verfügbar, ist dieses Array leer.

* Mindestanzahl: 0




| assetName | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem von Kubernetes zugewiesenen Namen. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 254




| Namensraum | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem von Kubernetes zugewiesenen Namespace. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 254




| Metadaten | link:#type_astra_metadata["type_astra_metadata"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra Metadatenschema


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appAsset",
  "version": "1.1",
  "id": "6415e851-b820-553b-9432-ebd057d1917d",
  "assetType": "Pod",
  "creationTimestamp": "2020-08-06T12:24:52.256624Z",
  "GVK": {
    "group": "apps",
    "kind": "Pod",
    "version": "v1"
  },
  "assetID": "93ec0c61-d993-4aa1-bb08-f4dcdd5e97f6",
  "labels": [
    {
      "name": "app",
      "value": "mediawiki"
    },
    {
      "name": "pod-template-hash",
      "value": "69c6fcf864"
    }
  ],
  "assetName": "mediawiki-69c6fcf864-2wx6l",
  "namespace": "wiki",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
GVK

JSON-Objekt, das eine Kubernetes-Gruppe/Version/Kind enthält.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Gruppe | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer von Kubernetes zugewiesenen Gruppenkennung. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 254




| Art | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die einen von Kubernetes zugewiesenen Kindbezeichner enthält. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 254




| Version | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer von Kubernetes zugewiesenen Versionskennung. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 254


|===
[role="api-collapsible-fifth-title"]
type_json

JSON-Objekt, das den gesamten Inhalt der Kubernetes-Ressourcendefinition enthält.

[role="api-collapsible-fifth-title"]
Etiketten

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
JSON-Zeichenkette mit dem Labelnamen Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63
* Der definierte reguläre Ausdruck ist: "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| Wert | Zeichenkette | True  a| 
JSON-Zeichenkette, die den Label-Wert enthält Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63
* Der definierte reguläre Ausdruck lautet: "^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra Metadatenschema


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | True  a| 



| CreationZeitstempel | Zeichenkette | True  a| 



| Änderungszeitstempel | Zeichenkette | True  a| 



| Erstellt von | Zeichenkette | True  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====