---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-topology-v1-clouds-clusters.html 
summary: Erstellen Sie einen neuen Cluster für eine Cloud 
---
= Erstellen Sie einen neuen Cluster für eine Cloud
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds/{cloud_id}/clusters`#

Gibt die gewünschten Werte für die zu erstellende Cluster-API-Ressource an.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| cloud_id | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Cloud-Ressource

|===


== Anfragetext

Gibt die gewünschten Werte für die zu erstellende Cluster-API-Ressource an.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-cluster"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"
* "1,1"
* "1,2"
* "1,3"
* "1,4"
* "1,5"




| Name | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Namen für den Cluster. Falls kein Name angegeben wird, wird der Kubernetes-Name des Clusters verwendet. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63
* Diese Zeichenkette wird intern validiert, um XSS-, Unicode-, Directory-Traversal- und SQL-Injection-Angriffe zu verhindern




| accHost | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die angibt, dass dieser Cluster die Instanz von Astra Control Center hostet, auf die derzeit zugegriffen wird. Folgende Werte sind definiert:

* "true" - Dieser Cluster hostet die Instanz des Astra Control Center, die aktuell aufgerufen wird.




| Anmeldeinformations-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der die ID der Anmeldeinformation angibt, die die kubeconfig-Datei für den Cluster enthält. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema. Wenn privateRouteID und connectorCapabilities mit mindestens der Relay-Option angegeben sind, ist credentialID optional. Wenn sie nicht angegeben sind, ist credentialID erforderlich, andernfalls wird ein Fehler generiert. Wenn credentialID und ein Relay-fähiger Connector angegeben sind, wird ein Fehler generiert.




| privateRouteID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der Standort-ID für private Cluster.

* Mindestlänge: 1
* Maximale Länge: 255




| connectorCapabilities | Array[string] | Falsch  a| 
Funktionen des mit diesem Cluster verknüpften Konnektors. Optional aus Gründen der Abwärtskompatibilität. Falls nicht angegeben, wird die Proxy-Funktionalität angenommen.



| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-cluster",
  "version": "1.5",
  "name": "GKE-22",
  "credentialID": "6fa2f917-f730-41b8-9c15-17f531843b31"
}
----
====


== Antwort

[source]
----
Status: 201, Returns the newly created cluster resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-cluster"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"
* "1,1"
* "1,2"
* "1,3"
* "1,4"
* "1,5"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Namen für den Cluster. Falls kein Name angegeben wird, wird der Kubernetes-Name des Clusters verwendet. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63
* Diese Zeichenkette wird intern validiert, um XSS-, Unicode-, Directory-Traversal- und SQL-Injection-Angriffe zu verhindern




| Zustand | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der den Betriebszustand des Clusters angibt. Folgende Werte sind definiert:

* „pending“ – Das Cluster ist zur Erkennung vorgesehen
* „discovering“ – Der Cluster befindet sich im Entdeckungsprozess
* „Bereitstellung“ – Der Cluster wird gerade bereitgestellt
* "läuft" - Der Cluster läuft normal
* „Fehlgeschlagen“ – Der Cluster befindet sich in einem permanenten Fehlerzustand
* „removed“ – Der Cluster ist derzeit nicht erreichbar
* "unbekannt" – Der Clusterstatus kann nicht ermittelt werden




| stateUnready | Array[string] | True  a| 
JSON-Array mit JSON-Strings, die jeweils einen Grund dafür angeben, warum der Cluster nicht in den Status „running“ wechseln kann, wenn im Status „running“ Probleme auftreten oder warum er in den Status „failed“ oder „removed“ gewechselt ist. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 127




| managedState | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der den Verwaltungsstatus des Clusters angibt. Folgende Werte sind definiert:

* „pending“ – Der Cluster ist zur Entdeckung oder zum Hinzufügen geplant
* „Nicht berechtigt“ – Der Cluster befindet sich im Status „Wird ausgeführt“, wird nicht verwaltet und ist nicht für die Verwaltung geeignet. Die Gründe für diese Nichtberechtigung sind im Wert des Schlüssels „unready“ angegeben.
* „Nicht verwaltet“ – Der Cluster befindet sich im Status „Läuft“ oder „Fehlgeschlagen“, wird nicht verwaltet und ist für die Verwaltung geeignet
* „managing“ – Der Cluster befindet sich im Status „running“ und wird gerade verwaltet.
* „managed“ – Der Cluster befindet sich im Status „running“, „failed“ oder „removed“ und wird verwaltet.




| protectionState | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der den Schutzstatus des Clusters angibt. Folgende Werte sind definiert:

* "vollständig" – Die Standard-Speicherklasse des Clusters unterstützt Snapshots
* "partiell" – Der Cluster verfügt nur über storageClasses, die keine Snapshots unterstützen
* "atRisk" - Die Standard-Speicherklasse des Clusters unterstützt keine Snapshots




| protectionStateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | True  a| 
Ein JSON-Array mit JSON-Objekten, das zusätzliche Details zum aktuellen Schutzstatus auflistet, einschließlich der Gründe, warum der aktuelle Status erreicht wurde. Sind keine Details verfügbar, ist dieses Array leer. Folgende Werte sind definiert:

* Mindestanzahl: 0




| restoreTargetSupported | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der angibt, ob der Cluster als Ziel für Anwendungsdatenverwaltungsoperationen geeignet ist. Folgende Werte sind definiert:

* "true" - Cluster ist ein geeignetes Ziel für App-Datenverwaltungsoperationen.
* "false" - Cluster ist _kein_ geeignetes Ziel für App-Datenverwaltungsoperationen.




| snapshotSupported | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der die Fähigkeit des Clusters zur Durchführung von Backup-ähnlichen Operationen im Bereich der Anwendungsdatenverwaltung angibt. Folgende Werte sind definiert:

* "true" - Cluster ist berechtigt, Anwendungsdatenverwaltungsoperationen durchzuführen.
* "false" - Der Cluster ist _nicht_ berechtigt, Anwendungsdatenverwaltungsoperationen durchzuführen.




| managedStateUnready | Array[string] | True  a| 
JSON-Array mit JSON-Zeichenketten, die jeweils einen Grund dafür angeben, warum der Cluster nicht verwaltet werden kann, oder dass der Cluster verwaltet wird, aber nicht schwerwiegende Fehler bei der Verwaltung des Clusters aufgetreten sind. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 127




| managedTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem Zeitstempel, der angibt, wann der Cluster unter Verwaltung gestellt wurde. Folgende Werte sind definiert:

* Entspricht dem ISO-8601 Datums- und Zeitschema. Dieser Schlüssel wird nur zurückgegeben, wenn ein Cluster einen managedState von „managed“ hat.




| tridentVersion | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der auf dem Cluster installierten Trident-Version. Folgende Werte sind definiert:

* Entspricht dem Softwareversionsschema




| tridentManagedState | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die einen von mehreren aufgezählten Werten enthält und den Verwaltungsstatus von Trident auf diesem Cluster angibt. Folgende Werte sind definiert:

* „Verwaltet“ – Trident Instanz im Cluster wird von Astra verwaltet
* „Unmanaged“ – Trident Instanz im Cluster wird nicht von Astra verwaltet




| tridentManagedStateDesired | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den gewünschten Verwaltungsstatus für Trident angibt. Folgende Werte sind definiert:

* "Verwaltet" – Trident auf diesem Cluster verwalten
* „Nicht verwaltet“ – Trident auf diesem Cluster nicht verwalten




| tridentManagedStateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falsch  a| 
JSON-Array mit JSON-Objekten, das zusätzliche Details darüber auflistet, warum der Status zu „verwaltet“ oder „nicht verwaltet“ gewechselt hat. + Falls keine Details verfügbar sind, ist dieses Array leer.

* Mindestanzahl: 0




| tridentManagedStateAllowed | Array[string] | Falsch  a| 
Zustände, die in einem gegebenen tridentManagedState angefordert werden können. Die folgenden Zustände können in jedem definierten Zustand angefordert werden:

* "verwaltet": "verwaltet"
* "unmanaged": "unverwaltet"




| inUse | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der angibt, ob der Cluster verwaltete Anwendungen enthält und daher nicht gelöscht werden kann. Folgende Werte sind definiert:

* „false“ – Der Cluster wird nicht verwaltet oder er wird zwar verwaltet, aber es sind keine verwalteten Anwendungen damit verknüpft
* „true“ – Der Cluster wird verwaltet und hat zugehörige verwaltete Anwendungen.




| accHost | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die angibt, dass dieser Cluster die Instanz von Astra Control Center hostet, auf die derzeit zugegriffen wird. Folgende Werte sind definiert:

* "true" - Dieser Cluster hostet die Instanz des Astra Control Center, die aktuell aufgerufen wird.




| clusterType | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der den Clustertyp angibt. Folgende Werte sind definiert:

* "gke" - Kubernetes, gehostet auf der Google Kubernetes Engine
* "aks" - Kubernetes, gehostet auf Microsoft Azure Kubernetes Service
* "eks" - Kubernetes, gehostet auf Amazon Elastic Kubernetes Service
* "rke" – Der Cluster ist vom Typ Rancher
* "tanzu" – Der Cluster ist vom Typ Tanzu Kubernetes Grid
* "openshift" - Der Cluster ist vom Typ OpenShift
* "kubernetes" - Der Cluster ist ein generisches Kubernetes




| clusterVersion | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der die semantische Versionsdarstellung der Clusterumgebung angibt. Bei Kubernetes-Clustern ist dies die Kubernetes-Version. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 31




| clusterVersionString | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der die erweiterten Versionsinformationen für die Clusterumgebung angibt. Für Kubernetes-Cluster ist dies die vollständige Kubernetes-Version. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 31




| clusterCreationTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem Zeitstempel, der angibt, wann der Cluster ursprünglich erstellt wurde. Folgende Werte sind definiert:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Namensräume | Array[string] | Falsch  a| 
JSON-Array von JSON-Zeichenketten, die jeweils einen Namespace innerhalb des Clusters angeben. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 253




| defaultStorageClass | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer Speicherklassen-ID, die der in Kubernetes festgelegten Standard-Speicherklasse entspricht. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| cloudID | Zeichenkette | True  a| 
JSON-Zeichenkette mit einem Wert, der die ID der Cloud angibt, auf der der Cluster ausgeführt wird. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Anmeldeinformations-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der die ID der Anmeldeinformation angibt, die die kubeconfig-Datei für den Cluster enthält. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema. Wenn privateRouteID und connectorCapabilities mit mindestens der Relay-Option angegeben sind, ist credentialID optional. Wenn sie nicht angegeben sind, ist credentialID erforderlich, andernfalls wird ein Fehler generiert. Wenn credentialID und ein Relay-fähiger Connector angegeben sind, wird ein Fehler generiert.




| Standort | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der von der Cloud bereitgestellt wird, auf der der Cluster ausgeführt wird und den cloudspezifischen Standort des Clusters angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63




| isMultizonal | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der von der Cloud bereitgestellt wird, auf der der Cluster ausgeführt wird, und angibt, ob sich der Cluster über zwei oder mehr Verfügbarkeitszonen erstreckt. Folgende Werte sind definiert:

* "wahr" - Der Cluster erstreckt sich über zwei oder mehr Verfügbarkeitszonen
* "falsch" - Der Cluster befindet sich vollständig innerhalb einer einzigen Verfügbarkeitszone




| privateRouteID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der Standort-ID für private Cluster.

* Mindestlänge: 1
* Maximale Länge: 255




| connectorCapabilities | Array[string] | Falsch  a| 
Funktionen des mit diesem Cluster verknüpften Konnektors. Optional aus Gründen der Abwärtskompatibilität. Falls nicht angegeben, wird die Proxy-Funktionalität angenommen.



| apiServiceID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der UUID des Kubernetes (k8s) API-Service-Objekts. Wird zur eindeutigen Identifizierung eines Clusters verwendet.



| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-cluster",
  "version": "1.5",
  "id": "547e24b9-ddf4-558f-8397-e97e732868e4",
  "name": "GKE-22",
  "state": "running",
  "stateUnready": [],
  "managedState": "unmanaged",
  "managedStateUnready": [],
  "protectionState": "full",
  "protectionStateDetails": [],
  "tridentVersion": "21.07.2",
  "tridentManagedState": "managed",
  "tridentManagedStateDetails": [],
  "inUse": "false",
  "clusterType": "kubernetes",
  "clusterVersion": "1.91.1",
  "clusterVersionString": "1.19.1",
  "clusterCreationTimestamp": "2020-08-06T12:24:52.256624Z",
  "namespaces": [
    "kube-system",
    "kube-public",
    "my-app-1"
  ],
  "defaultStorageClass": "31c95aba-99d9-4987-b1bb-000dfce5952c",
  "cloudID": "548bdc1f-f00e-4a23-a062-83265d224d46",
  "credentialID": "6fa2f917-f730-41b8-9c15-17f531843b31",
  "location": "europe-west4",
  "isMultizonal": "false",
  "apiServiceID": "6bf33af2-872a-4553-a891-26b510c3edbe",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Antwort

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/64",
  "title": "Storage classes not found",
  "detail": "Storage classes from Trident weren't found.",
  "status": "500"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | True  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====