---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-groups.html 
summary: Neue Gruppe erstellen 
---
= Neue Gruppe erstellen
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/groups`#

Gibt die gewünschten Werte für die zu erstellende Group-API-Ressource an.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | True  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}


|===


== Anfragetext

Gibt die gewünschten Werte für die zu erstellende Group-API-Ressource an.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-group"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"
* "1,1"




| Name | Zeichenkette | Falsch  a| 
Der Name der Gruppenressource. Falls beim Erstellen nicht angegeben, wird der Wert auf

* erster Common Name (CN) Relative Distinguished Names (RDN), falls in der authID gefunden,
* authID, andernfalls. Wird beim Aktualisieren kein Wert angegeben, bleibt der Wert unverändert erhalten. Folgende Werte sind definiert:
* Mindestlänge: 1
* Maximale Länge: 2048




| authProvider | Zeichenkette | True  a| 
Der Authentifizierungsanbieter für die Gruppenressource. Folgende Werte sind definiert:

* "ldap"




| authID | Zeichenkette | True  a| 
Der Distinguished Name (DN) einer LDAP-Gruppe. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 2048




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-group",
  "version": "1.1",
  "name": "engineering-group",
  "authProvider": "ldap",
  "authID": "CN=Engineering,CN=Groups,DC=example,DC=com"
}
----
====


== Antwort

[source]
----
Status: 201, Returns the newly created group resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 
Medientyp der Ressource. Folgende Werte sind definiert:

* "application/astra-group"




| Version | Zeichenkette | True  a| 
Version der Ressource. Folgende Werte sind definiert:

* "1,0"
* "1,1"




| id | Zeichenkette | True  a| 
Weltweit eindeutiger Bezeichner der Ressource. Folgende Werte sind definiert:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | True  a| 
Der Name der Gruppenressource. Falls beim Erstellen nicht angegeben, wird der Wert auf

* erster Common Name (CN) Relative Distinguished Names (RDN), falls in der authID gefunden,
* authID, andernfalls. Wird beim Aktualisieren kein Wert angegeben, bleibt der Wert unverändert erhalten. Folgende Werte sind definiert:
* Mindestlänge: 1
* Maximale Länge: 2048




| authProvider | Zeichenkette | True  a| 
Der Authentifizierungsanbieter für die Gruppenressource. Folgende Werte sind definiert:

* "ldap"




| authID | Zeichenkette | True  a| 
Der Distinguished Name (DN) einer LDAP-Gruppe. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 2048




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-group",
  "version": "1.1",
  "id": "77754011-b93f-515e-a145-5a343aecdece",
  "name": "engineering-group",
  "authProvider": "ldap",
  "authID": "CN=Engineering,CN=Groups,DC=example,DC=com",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/14",
  "title": "Unauthorized access",
  "detail": "The user isn't enabled.",
  "status": "403"
}
----
====


== Antwort

[source]
----
Status: 406, Not acceptable
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/32",
  "title": "Unsupported content type",
  "detail": "The response can't be returned in the requested format.",
  "status": "406"
}
----
====


== Antwort

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
----
====


== Fehler

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | True  a| 



| Titel | Zeichenkette | True  a| 



| Detail | Zeichenkette | True  a| 



| Status | Zeichenkette | True  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/7",
  "title": "Invalid JSON payload",
  "detail": "The request body is not valid JSON.",
  "status": "400"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 



| Wert | Zeichenkette | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Metadatenschema. Falls beim Erstellen keine Bezeichnung angegeben wird, wird ein Metadatenobjekt ohne Bezeichnungen erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | True  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | True  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | True  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====